Fix IndexError: pop from empty list
The program ended up consuming a lot of CPU time and spewing this error:

```
IndexError: pop from empty list
12:01:48.086 Exception in callback AsyncioBlockingUHID._async_writer()
handle: <Handle AsyncioBlockingUHID._async_writer()>
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3/dist-packages/fido2ble/vendored/uhid/__init__.py", line 374, in _async_writer
    self._write(self._write_queue.pop(0))
                ^^^^^^^^^^^^^^^^^^^^^^^^
```

If the list is empty, the exception was preventing the removal of the writer.

Closes #6